### ISSUE TITLE
Problem of reproducing the angelix test

### ISSUE THREAD

**Issue by DehengYang** [mechtaev/angelix#10]
> Sorry for disturbing you with this question. I download the source code of Angelix and configure it as indicated by the README.md. However, I failed to reproduce all tests of Angelix and Semfix ( I configured Semfix also, with `make semfix` command). For example, the output of running `make test-semfix` is as follow:

 ```
dehengyang@dehengyang:~/Semifix/angelix-master$ . activate 
 dehengyang@dehengyang:~/Semifix/angelix-master$ make test-semfix
 python3 tests/semfix-tests.py
 FF
 ====================================================================
 FAIL: test_semfix (__main__.TestAngelix)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "tests/semfix-tests.py", line 36, in test_semfix
     self.assertEqual(result, 'SUCCESS')
 AssertionError: 'FAIL' != 'SUCCESS'
 - FAIL
 + SUCCESS
 
 
 ====================================================================
 FAIL: test_semfix_synthesis (__main__.TestAngelix)
 ----------------------------------------------------------------------
 Traceback (most recent call last):
   File "tests/semfix-tests.py", line 42, in test_semfix_synthesis
     self.assertEqual(result, 'SUCCESS')
 AssertionError: 'FAIL' != 'SUCCESS'
 - FAIL
 + SUCCESS

 ----------------------------------------------------------------------
 Ran 2 tests in 0.860s
 
 FAILED (failures=2)
 make: *** [test-semfix] Error 1

```
Then, I tried to explore the reasons why this failed. I reproduced the whole folder of distance.c according to the  **Tutorial.md**. I run the command 
```
. activate
bugs=distance
bugDir=/home/dehengyang/Semifix/angelix-master/tests/$bugs
cd $bugDir
angelix src distance.c oracle 1 2 3 --assert assert.json 
```
However, angelix still failed to repair this bug. The output is:

> INFO     project         configuring validation source
> INFO     project         building json compilation database from validation source
> INFO     testing         running test '1' of validation source
> INFO     testing         running test '2' of validation source
> INFO     testing         running test '3' of validation source
> INFO     project         configuring frontend source
> INFO     transformation  instrumenting repairable of frontend source
> INFO     project         building frontend source
> INFO     repair          running positive tests for debugging
> INFO     testing         running test '1' of frontend source
> INFO     testing         running test '2' of frontend source
> INFO     repair          running negative tests for debugging
> INFO     testing         running test '3' of frontend source
> INFO     localization    selected expressions [(12, 14, 12, 19)] with group score 1.0 
> INFO     localization    selected expressions [(6, 14, 6, 19)] with group score 0.5 
> INFO     localization    selected expressions [(5, 9, 5, 14)] with group score 0.33333 
> INFO     localization    selected expressions [(9, 9, 9, 14)] with group score 0.33333 
> INFO     localization    selected expressions [(13, 9, 13, 14)] with group score 0.33333 
> INFO     repair          considering suspicious expressions [(12, 14, 12, 19)]
> INFO     reduction       selected 1 tests
> INFO     reduction       selected passing tests: []
> INFO     reduction       selected failing tests: ['3']
> INFO     project         configuring backend source
> INFO     transformation  instrumenting suspicious of backend source
> INFO     project         building backend source
> INFO     inference       inferring specification for test '3'
> INFO     testing         running test '3' of backend source with KLEE
> INFO     inference       sleeping for 1 second...
> WARNING  inference       No paths explored
> INFO     repair          considering suspicious expressions [(6, 14, 6, 19)]
> INFO     reduction       selected 1 tests
> INFO     reduction       selected passing tests: []
> INFO     reduction       selected failing tests: ['3']
> INFO     project         configuring backend source
> INFO     transformation  instrumenting suspicious of backend source
> INFO     project         building backend source
> INFO     inference       inferring specification for test '3'
> INFO     testing         running test '3' of backend source with KLEE
> INFO     inference       sleeping for 1 second...
> WARNING  inference       No paths explored
> INFO     repair          considering suspicious expressions [(5, 9, 5, 14)]
> INFO     reduction       selected 1 tests
> INFO     reduction       selected passing tests: []
> INFO     reduction       selected failing tests: ['3']
> INFO     project         configuring backend source
> INFO     transformation  instrumenting suspicious of backend source
> INFO     project         building backend source
> INFO     inference       inferring specification for test '3'
> INFO     testing         running test '3' of backend source with KLEE
> INFO     inference       sleeping for 1 second...
> WARNING  inference       No paths explored
> INFO     repair          considering suspicious expressions [(9, 9, 9, 14)]
> INFO     reduction       selected 1 tests
> INFO     reduction       selected passing tests: []
> INFO     reduction       selected failing tests: ['3']
> INFO     project         configuring backend source
> INFO     transformation  instrumenting suspicious of backend source
> INFO     project         building backend source
> INFO     inference       inferring specification for test '3'
> INFO     testing         running test '3' of backend source with KLEE
> INFO     inference       sleeping for 1 second...
> WARNING  inference       No paths explored
> INFO     repair          considering suspicious expressions [(13, 9, 13, 14)]
> INFO     reduction       selected 1 tests
> INFO     reduction       selected passing tests: []
> INFO     reduction       selected failing tests: ['3']
> INFO     project         configuring backend source
> INFO     transformation  instrumenting suspicious of backend source
> INFO     project         building backend source
> INFO     inference       inferring specification for test '3'
> INFO     testing         running test '3' of backend source with KLEE
> INFO     inference       sleeping for 1 second...
> WARNING  inference       No paths explored
> INFO     repair          no patch generated in 5s
> FAIL
(I am sorry that due to the problem of uploading the file, I copy the whole text of the output rather than upload a file.) 
This output is quite different from the expected output given by `Tutorial.md`.

Much appreciated if any help is provided.

**Comment by mechtaev** [comment]
@DehengYang This looks like an issue with KLEE. Maybe it is not built correctly for some reason? You could try to run with `--verbose` to get more information.

**Comment by DehengYang** [comment]
Thank you so much for your great help! I will try this later.
