### ISSUE TITLE
https://git.llvm.org/git/clang-tools-extra not accessible

### ISSUE THREAD

**Issue by thierry-tct** [mechtaev/angelix#19]
`https://git.llvm.org/git/clang-tools-extra` is no more accessible.

In Makefile, CLANG_TOOLS_EXTRA_URL should be changed to the following:
```
CLANG_TOOLS_EXTRA_URL=https://github.com/llvm-mirror/clang-tools-extra.git
```

**Comment by joerenzullo** [comment]
Thanks for posting your solution, @thierry-tct ; I also ran into this issue, and your suggestion fixed it for me. I'll create a pull request.

**Comment by yxliang01** [comment]
Is the Github mirror official? If not, there might be other issues though.
