### ISSUE TITLE
compiling failed

### ISSUE THREAD

**Issue by saiema** [mechtaev/angelix#22]
Installed all dependencies:

after `make default` obtained several compilation errors (attached is a log file)

some of these errors include

`/home/stein/Desktop/Projects/angelix/build/llvm-2.9/include/llvm/Operator.h:209:7: error: deleted function ‘virtual llvm::GEPOperator::~GEPOperator()’ overriding non-deleted function
  209 | class GEPOperator
      |       ^~~~~~~~~~~
`

[compilation.log](https://github.com/mechtaev/angelix/files/6208093/compilation.log)

**Comment by saiema** [comment]
Addding CXXFLAGS="-Wno-delete-non-virtual-dtor" I managed to make compilation pass the point of the previous errors, but now I got

`/home/stein/Desktop/Projects/angelix/build/llvm-2.9/include/llvm/ADT/IntervalMap.h:1973:45: error: expected primary-expression before ‘>’ token
 1973 |     Node[NewNode] = this->map->newNode<NodeT>();
|                                             ^
/home/stein/Desktop/Projects/angelix/build/llvm-2.9/include/llvm/ADT/IntervalMap.h:1973:47: error: expected primary-expression before ‘)’ token
 1973 |     Node[NewNode] = this->map->newNode<NodeT>();
      |                                               ^
`

[compilation.log](https://github.com/mechtaev/angelix/files/6208523/compilation.log)

**Comment by mechtaev** [comment]
Are you using the versions of dependencies (e.g. OS) as specified in the instruction? The current version of Angelix depends on some old libraries which do not compile under new OSes.

**Comment by saiema** [comment]
Hi, I'm using Ubuntu 20.04 but I don't know which libraries are required, I tried compiling the Dockerfile but I end with one failing test (mentioned in another issue)

**Comment by mechtaev** [comment]
It requires Ubuntu 14.04 because of the old version of llvm
