### ISSUE TITLE
Angelix docker version failed test

### ISSUE THREAD

**Issue by saiema** [mechtaev/angelix#23]
There is a failing test on the docker version of Angelix

```
======================================================================
FAIL: test_deletebreak (__main__.TestAngelix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/tests.py", line 126, in test_deletebreak
    self.assertEqual(result, 'SUCCESS')
AssertionError: 'FAIL' != 'SUCCESS'
- FAIL
+ SUCCESS


----------------------------------------------------------------------
Ran 17 tests in 209.562s

```

**Comment by mechtaev** [comment]
Thanks. This functionality is not supported. We are not fixing it, because the current version of Angelix has many old dependencies, so we are going to update nearly everything after we finish some research.

**Comment by saiema** [comment]
But what it means the functionality is not supported? Can I overlook the failing test to use Angelix?

**Comment by mechtaev** [comment]
I mean the delete break functionality. You can still use it without it. It is not really very important.

**Comment by saiema** [comment]
Ok, thank you

Regards.
