### ISSUE TITLE
Angelix example from `Tutorial.md` fails to find a repair with `--instr-printf distance.c`

### ISSUE THREAD

**Issue by pdreiter** [mechtaev/angelix#30]
1. I'm currently working on this commit `01396ac20e1e973834d0fd4eccbc7e24216d37d0` [currently origin/master HEAD]
2. Angelix was successfully able to find a repair using the `distance.c` example from `Manual.md`, which contains some instrumentation.
3. When I stripped `distance.c` of the Angelix instrumentation and applied `--instr-printf distance.c` to the Angelix command line, Angelix was unable to find a repair.

Here is some preliminary debug info:
Looking at the differences between runs and Angelix log output, I'm seeing this in the `--instr-printf` angelix.log:
`INFO     inference       value 'stdout' executed 0 times while 1 required`

while diff'ing the `backend/distance.c` between the baseline (`<`) and instr-print (`>`), this difference is the culprit of the logfile's inference note:
```
1,3d0
< #include <stdio.h>
< #include <stdlib.h>
<
7a5,8
> #include <stdio.h>
> #include <stdlib.h>
>
>
17c18
<         dy = ANGELIX_CHOOSE(int, y1 - y2, 17, 14, 17, 19, ((char*[]){"y1", "y2"}), ((int[]){y1, y2}), 2);
---
>         dy = y1 - y2;
30c31
<     printf("%d\n", ANGELIX_OUTPUT(int, distance(x1, y1, x2, y2), "stdout"));
---
>     ({ if (ANGELIX_CHOOSE(bool, 1, 31, 12, 31, 12, ((char*[]){"y1", "x1", "x2", "y2"}), ((int[]){y1, x1, x2, y2}), 4)) printf("%d\n", ANGELIX_OUTPUT(int, distance(x1, y1, x2, y2), "angelixVar11")); });
```

**Comment by pdreiter** [comment]
I completely understand that this is not an actively maintained tool and any forward progress on this issue would be unexpected.

**Comment by mechtaev** [comment]
@pdreiter , since the logs say `INFO inference value 'stdout' executed 0 times while 1 required`, it means that label `"stdout"` is still expected even though it is not used in the instrumentation. Maybe you need to change "assert.json", or use the golden version to infer the expected values.

**Comment by pdreiter** [comment]
ahh, converting to using a `--golden <dir>` in lieu of assert.json did the trick! Thanks!
